name: Destroy Lambda

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../lambda.zip .

      - name: Retrieve Terraform state
        run: |
          git fetch origin state
          git checkout state
          mv terraform/state/terraform.tfstate terraform/

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform
